### PR TITLE
Add light gray background

### PR DESCRIPTION
**Pull request by hdavidzhu**
image

### CODE REVIEW

**Review by jgozal — APPROVED** [review]
thanks for taking care david! Please let me know before deploying so that I can fix quickly the domain in the repo's settings and avoid 404s for those using the site

**Comment by jgozal** [comment]
@hdavidzhu I just noticed the green box still has a white background (looking at the screenshot). Is that intended?

**Comment by jgozal** [comment]
sug: not sure if you've tried to see how this looks, but I just realized other sites try to put sort of the inputs with a greyish/purple background, and the results with a white background. Not really sure what the rule for this is, if there is one.

image

image

image

**Comment by hdavidzhu** [comment]
Hmm yeah I saw that too, but it may be good, as it matches closer w/ the card

**Pull request merged**
